# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_block_design/axi_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design || ORIG_REF_NAME==axi_block_design} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_dma_0_0/axi_block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_dma_0_0 || ORIG_REF_NAME==axi_block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_processing_system7_0_0/axi_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_processing_system7_0_0 || ORIG_REF_NAME==axi_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_dma_add_one_0_0/axi_block_design_dma_add_one_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_dma_add_one_0_0 || ORIG_REF_NAME==axi_block_design_dma_add_one_0_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_smc_1/axi_block_design_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_smc_1 || ORIG_REF_NAME==axi_block_design_axi_smc_1} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_rst_ps7_0_100M_0/axi_block_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_block_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_xbar_0/axi_block_design_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_0/axi_block_design_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_us_0/axi_block_design_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_1/axi_block_design_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_us_1/axi_block_design_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_0/axi_block_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_block_design_axi_mem_intercon_0 || ORIG_REF_NAME==axi_block_design_axi_mem_intercon_0} -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/AXI_lite/AXI_lite.gen/sources_1/bd/axi_block_design/axi_block_design_ooc.xdc
