# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ivanyuchen/CODING_FILES/VERILOG/AXI_lite/AXI_lite.srcs/sources_1/bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_0/axi_block_design_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'axi_block_design_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/AXI_lite/AXI_lite.gen/sources_1/bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_0/axi_block_design_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_block_design_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ivanyuchen/CODING_FILES/VERILOG/AXI_lite/AXI_lite.srcs/sources_1/bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_0/axi_block_design_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'axi_block_design_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/AXI_lite/AXI_lite.gen/sources_1/bd/axi_block_design/ip/axi_block_design_axi_mem_intercon_imp_auto_pc_0/axi_block_design_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_block_design_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
