# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PCSNN_block_design/PCSNN_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design || ORIG_REF_NAME==PCSNN_block_design} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_processing_system7_0_0/PCSNN_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_processing_system7_0_0 || ORIG_REF_NAME==PCSNN_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_dma_0_0 || ORIG_REF_NAME==PCSNN_block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_snn_dma_wrapper_0_0 || ORIG_REF_NAME==PCSNN_block_design_snn_dma_wrapper_0_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_smc_0/PCSNN_block_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_smc_0 || ORIG_REF_NAME==PCSNN_block_design_axi_smc_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_rst_ps7_0_100M_0/PCSNN_block_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==PCSNN_block_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_imp_xbar_0/PCSNN_block_design_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_0/PCSNN_block_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_0 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_imp_auto_pc_0/PCSNN_block_design_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_imp_auto_us_0/PCSNN_block_design_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_imp_auto_pc_1/PCSNN_block_design_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/PCSNN_block_design/ip/PCSNN_block_design_axi_mem_intercon_imp_auto_us_1/PCSNN_block_design_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==PCSNN_block_design_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/PCSNN_block_design_ooc.xdc
