// Generated by verilog/generate_weight_mem.py

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_000.mem")
  ) w_bram_inst_000 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[0])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_001.mem")
  ) w_bram_inst_001 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[1])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_002.mem")
  ) w_bram_inst_002 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[2])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_003.mem")
  ) w_bram_inst_003 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[3])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_004.mem")
  ) w_bram_inst_004 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[4])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_005.mem")
  ) w_bram_inst_005 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[5])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_006.mem")
  ) w_bram_inst_006 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[6])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_007.mem")
  ) w_bram_inst_007 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[7])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_008.mem")
  ) w_bram_inst_008 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[8])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_009.mem")
  ) w_bram_inst_009 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[9])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_010.mem")
  ) w_bram_inst_010 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[10])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_011.mem")
  ) w_bram_inst_011 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[11])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_012.mem")
  ) w_bram_inst_012 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[12])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_013.mem")
  ) w_bram_inst_013 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[13])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_014.mem")
  ) w_bram_inst_014 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[14])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_015.mem")
  ) w_bram_inst_015 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[15])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_016.mem")
  ) w_bram_inst_016 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[16])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_017.mem")
  ) w_bram_inst_017 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[17])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_018.mem")
  ) w_bram_inst_018 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[18])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_019.mem")
  ) w_bram_inst_019 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[19])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_020.mem")
  ) w_bram_inst_020 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[20])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_021.mem")
  ) w_bram_inst_021 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[21])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_022.mem")
  ) w_bram_inst_022 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[22])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_023.mem")
  ) w_bram_inst_023 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[23])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_024.mem")
  ) w_bram_inst_024 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[24])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_025.mem")
  ) w_bram_inst_025 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[25])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_026.mem")
  ) w_bram_inst_026 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[26])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_027.mem")
  ) w_bram_inst_027 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[27])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_028.mem")
  ) w_bram_inst_028 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[28])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_029.mem")
  ) w_bram_inst_029 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[29])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_030.mem")
  ) w_bram_inst_030 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[30])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_031.mem")
  ) w_bram_inst_031 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[31])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_032.mem")
  ) w_bram_inst_032 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[32])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_033.mem")
  ) w_bram_inst_033 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[33])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_034.mem")
  ) w_bram_inst_034 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[34])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_035.mem")
  ) w_bram_inst_035 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[35])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_036.mem")
  ) w_bram_inst_036 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[36])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_037.mem")
  ) w_bram_inst_037 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[37])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_038.mem")
  ) w_bram_inst_038 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[38])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_039.mem")
  ) w_bram_inst_039 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[39])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_040.mem")
  ) w_bram_inst_040 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[40])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_041.mem")
  ) w_bram_inst_041 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[41])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_042.mem")
  ) w_bram_inst_042 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[42])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_043.mem")
  ) w_bram_inst_043 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[43])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_044.mem")
  ) w_bram_inst_044 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[44])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_045.mem")
  ) w_bram_inst_045 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[45])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_046.mem")
  ) w_bram_inst_046 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[46])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_047.mem")
  ) w_bram_inst_047 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[47])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_048.mem")
  ) w_bram_inst_048 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[48])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_049.mem")
  ) w_bram_inst_049 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[49])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_050.mem")
  ) w_bram_inst_050 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[50])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_051.mem")
  ) w_bram_inst_051 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[51])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_052.mem")
  ) w_bram_inst_052 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[52])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_053.mem")
  ) w_bram_inst_053 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[53])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_054.mem")
  ) w_bram_inst_054 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[54])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_055.mem")
  ) w_bram_inst_055 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[55])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_056.mem")
  ) w_bram_inst_056 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[56])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_057.mem")
  ) w_bram_inst_057 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[57])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_058.mem")
  ) w_bram_inst_058 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[58])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_059.mem")
  ) w_bram_inst_059 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[59])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_060.mem")
  ) w_bram_inst_060 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[60])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_061.mem")
  ) w_bram_inst_061 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[61])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_062.mem")
  ) w_bram_inst_062 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[62])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_063.mem")
  ) w_bram_inst_063 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[63])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_064.mem")
  ) w_bram_inst_064 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[64])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_065.mem")
  ) w_bram_inst_065 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[65])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_066.mem")
  ) w_bram_inst_066 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[66])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_067.mem")
  ) w_bram_inst_067 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[67])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_068.mem")
  ) w_bram_inst_068 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[68])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_069.mem")
  ) w_bram_inst_069 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[69])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_070.mem")
  ) w_bram_inst_070 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[70])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_071.mem")
  ) w_bram_inst_071 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[71])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_072.mem")
  ) w_bram_inst_072 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[72])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_073.mem")
  ) w_bram_inst_073 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[73])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_074.mem")
  ) w_bram_inst_074 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[74])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_075.mem")
  ) w_bram_inst_075 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[75])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_076.mem")
  ) w_bram_inst_076 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[76])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_077.mem")
  ) w_bram_inst_077 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[77])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_078.mem")
  ) w_bram_inst_078 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[78])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_079.mem")
  ) w_bram_inst_079 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[79])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_080.mem")
  ) w_bram_inst_080 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[80])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_081.mem")
  ) w_bram_inst_081 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[81])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_082.mem")
  ) w_bram_inst_082 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[82])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_083.mem")
  ) w_bram_inst_083 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[83])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_084.mem")
  ) w_bram_inst_084 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[84])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_085.mem")
  ) w_bram_inst_085 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[85])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_086.mem")
  ) w_bram_inst_086 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[86])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_087.mem")
  ) w_bram_inst_087 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[87])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_088.mem")
  ) w_bram_inst_088 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[88])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_089.mem")
  ) w_bram_inst_089 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[89])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_090.mem")
  ) w_bram_inst_090 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[90])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_091.mem")
  ) w_bram_inst_091 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[91])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_092.mem")
  ) w_bram_inst_092 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[92])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_093.mem")
  ) w_bram_inst_093 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[93])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_094.mem")
  ) w_bram_inst_094 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[94])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_095.mem")
  ) w_bram_inst_095 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[95])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_096.mem")
  ) w_bram_inst_096 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[96])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_097.mem")
  ) w_bram_inst_097 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[97])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_098.mem")
  ) w_bram_inst_098 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[98])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_099.mem")
  ) w_bram_inst_099 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[99])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_100.mem")
  ) w_bram_inst_100 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[100])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_101.mem")
  ) w_bram_inst_101 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[101])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_102.mem")
  ) w_bram_inst_102 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[102])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_103.mem")
  ) w_bram_inst_103 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[103])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_104.mem")
  ) w_bram_inst_104 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[104])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_105.mem")
  ) w_bram_inst_105 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[105])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_106.mem")
  ) w_bram_inst_106 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[106])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_107.mem")
  ) w_bram_inst_107 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[107])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_108.mem")
  ) w_bram_inst_108 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[108])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_109.mem")
  ) w_bram_inst_109 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[109])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_110.mem")
  ) w_bram_inst_110 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[110])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_111.mem")
  ) w_bram_inst_111 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[111])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_112.mem")
  ) w_bram_inst_112 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[112])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_113.mem")
  ) w_bram_inst_113 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[113])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_114.mem")
  ) w_bram_inst_114 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[114])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_115.mem")
  ) w_bram_inst_115 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[115])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_116.mem")
  ) w_bram_inst_116 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[116])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_117.mem")
  ) w_bram_inst_117 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[117])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_118.mem")
  ) w_bram_inst_118 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[118])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_119.mem")
  ) w_bram_inst_119 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[119])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_120.mem")
  ) w_bram_inst_120 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[120])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_121.mem")
  ) w_bram_inst_121 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[121])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_122.mem")
  ) w_bram_inst_122 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[122])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_123.mem")
  ) w_bram_inst_123 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[123])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_124.mem")
  ) w_bram_inst_124 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[124])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_125.mem")
  ) w_bram_inst_125 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[125])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_126.mem")
  ) w_bram_inst_126 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[126])
  );

  w_bram #(
      .INPUT_DIM(INPUT_DIM),
      .WEIGHTS_FILE("/home/ivanyuchen/CODING_FILES/PC_SNN/verilog/weights/pc_snn_weight_127.mem")
  ) w_bram_inst_127 (
      .clk     (clk),
      .addr    (pixel_addr),
      .data_out(data_out[127])
  );
