# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.runs/PCSNN_block_design_snn_dma_wrapper_0_0_synth_1/PCSNN_block_design_snn_dma_wrapper_0_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "PCSNN_block_design_snn_dma_wrapper_0_0_synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_param chipscope.maxJobs 1
set_param general.usePosixSpawnForFork 1
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/mref
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.cache/wt [current_project]
set_property parent.project_path /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_039.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_012.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_057.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_081.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_055.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_098.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_020.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_014.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_063.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_103.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_049.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_006.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_071.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_040.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_002.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_010.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_053.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_113.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_126.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_059.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_029.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_096.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_016.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weights_flat.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_083.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_065.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_022.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_047.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_101.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_078.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_004.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_115.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_085.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_042.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_033.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_027.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_093.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_036.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_076.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_079.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_050.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_125.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_019.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_108.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_121.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_104.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_117.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_044.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_001.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_031.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_008.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_087.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_068.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_038.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_061.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_025.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_074.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_106.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_119.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_091.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_123.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_013.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_021.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_099.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_110.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_064.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_102.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_072.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_048.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_005.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_089.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_100.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_011.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_054.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_097.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_080.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_058.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_112.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_015.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_070.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_109.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_023.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_120.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_066.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_003.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_046.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_127.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_052.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_114.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_017.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_082.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_095.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_026.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_051.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_069.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_094.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_077.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_009.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_034.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_107.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_035.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_018.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_122.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_124.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_116.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_028.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_067.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_084.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_041.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_007.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_032.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_088.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_045.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_075.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_037.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_024.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_062.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_092.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_111.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_118.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_090.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_105.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_000.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_073.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_060.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_030.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_043.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_056.mem
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/weights/pc_snn_weight_086.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/verilog/SNN_layer.sv
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/verilog/SNN_top.sv
  /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/verilog/image_buffer.sv
}
read_verilog -library xil_defaultlib /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/imports/verilog/snn_dma_wrapper.v
read_ip -quiet /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top PCSNN_block_design_snn_dma_wrapper_0_0 -part xc7z020clg400-1 -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all PCSNN_block_design_snn_dma_wrapper_0_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PCSNN_block_design_snn_dma_wrapper_0_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file PCSNN_block_design_snn_dma_wrapper_0_0_utilization_synth.rpt -pb PCSNN_block_design_snn_dma_wrapper_0_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.runs/PCSNN_block_design_snn_dma_wrapper_0_0_synth_1/PCSNN_block_design_snn_dma_wrapper_0_0.dcp /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.ip_user_files/ip/PCSNN_block_design_snn_dma_wrapper_0_0]} {
  catch { 
    file copy -force /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_stub.v /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.ip_user_files/ip/PCSNN_block_design_snn_dma_wrapper_0_0
  }
}

if {[file isdir /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.ip_user_files/ip/PCSNN_block_design_snn_dma_wrapper_0_0]} {
  catch { 
    file copy -force /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_snn_dma_wrapper_0_0/PCSNN_block_design_snn_dma_wrapper_0_0_stub.vhdl /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.ip_user_files/ip/PCSNN_block_design_snn_dma_wrapper_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "PCSNN_block_design_snn_dma_wrapper_0_0_synth_1" END { }
