# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0.xci
# IP: The module: 'PCSNN_block_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.srcs/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0.xci
# IP: The module: 'PCSNN_block_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ivanyuchen/CODING_FILES/VERILOG/PCSNN/PCSNN.gen/sources_1/bd/PCSNN_block_design/ip/PCSNN_block_design_axi_dma_0_0/PCSNN_block_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCSNN_block_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
